import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';

const TermsOfServicePage: React.FC = () => {
  return (
    <div className="min-h-screen bg-gray-900 text-white">
      {/* Header */}
      <div className="bg-gray-800 border-b border-gray-700">
        <div className="max-w-4xl mx-auto px-4 py-6">
          <div className="flex items-center space-x-4">
            <Link 
              to="/" 
              className="flex items-center space-x-2 text-purple-400 hover:text-purple-300 transition-colors"
            >
              <ArrowLeft className="h-5 w-5" />
              <span>Back to Home</span>
            </Link>
          </div>
          <h1 className="text-3xl font-bold mt-4">Terms of Service</h1>
          <p className="text-gray-400 mt-2">Effective Date: January 1, 2025</p>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-4 py-8">
        <div className="prose prose-invert max-w-none">
          <div className="bg-gray-800 rounded-lg p-8 space-y-8">
            
            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">1. Introduction</h2>
              <p className="text-gray-300 leading-relaxed">
                Welcome to Zuexis ("we," "our," "us"). By accessing or using our service, located at 
                <a href="https://www.zuexis.com" className="text-purple-400 hover:text-purple-300"> https://www.zuexis.com</a>, 
                you ("user," "you," "your") agree to be bound by these Terms & Conditions. If you do not agree, do not use the service.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">2. Description of Service</h2>
              <p className="text-gray-300 leading-relaxed">
                Zuexis provides AI-powered tools that generate transcripts and create video clips for social media and related platforms. 
                The service is intended to assist creators in editing and repurposing content more efficiently. We do not guarantee viral 
                success, audience growth, or any specific outcome.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">3. User Content & Ownership</h2>
              <div className="text-gray-300 leading-relaxed space-y-2">
                <p>• You retain all rights to the videos and content you upload.</p>
                <p>• By using Zuexis, you grant us a limited, temporary license to process your files for the sole purpose of providing the service.</p>
                <p>• We do not claim ownership of your content.</p>
              </div>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">4. Payments & Subscriptions</h2>
              <div className="text-gray-300 leading-relaxed space-y-2">
                <p>• Zuexis offers both free and paid subscription tiers.</p>
                <p>• Paid subscriptions are billed through Stripe on a recurring basis (monthly or annually, depending on plan).</p>
                <p>• Refunds are not provided. Users may cancel at any time to avoid future charges.</p>
              </div>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">5. Restrictions on Use</h2>
              <p className="text-gray-300 leading-relaxed mb-2">Users may not:</p>
              <div className="text-gray-300 leading-relaxed space-y-2 ml-4">
                <p>• Upload content they do not own or lack rights to distribute.</p>
                <p>• Use Zuexis for illegal, abusive, obscene, or harmful purposes.</p>
                <p>• Attempt to reverse engineer, interfere with, or abuse the service.</p>
              </div>
              <p className="text-gray-300 leading-relaxed mt-4">
                We reserve the right to suspend or terminate accounts that violate these rules.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">6. Disclaimers</h2>
              <div className="text-gray-300 leading-relaxed space-y-2">
                <p>• Zuexis provides outputs generated by AI. We do not guarantee 100% accuracy, quality, or suitability.</p>
                <p>• We are not responsible for consequences arising from the use of our outputs, including (but not limited to) social platform bans, copyright claims, lost revenue, or reputational harm.</p>
                <p>• The service is provided "as is" without warranties of any kind.</p>
              </div>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">7. Termination</h2>
              <p className="text-gray-300 leading-relaxed">
                We reserve the right to suspend or terminate any account at our discretion, especially in cases of abuse, 
                nonpayment, or violation of these Terms.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">8. Governing Law</h2>
              <p className="text-gray-300 leading-relaxed">
                These Terms shall be governed by the laws of the State of Pennsylvania, United States. If Zuexis is later 
                organized as a Delaware LLC, disputes will instead fall under Delaware law.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">9. Modifications</h2>
              <p className="text-gray-300 leading-relaxed">
                We may update these Terms at any time. Continued use of the service after changes take effect constitutes 
                acceptance of the revised Terms.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">10. Contact</h2>
              <p className="text-gray-300 leading-relaxed">
                If you have questions about these Terms, please contact us at:
              </p>
              <div className="text-gray-300 leading-relaxed mt-2">
                <p>Email: <a href="mailto:zuexisclips@gmail.com" className="text-purple-400 hover:text-purple-300">zuexisclips@gmail.com</a></p>
                <p>Address: Prospect Park, PA</p>
              </div>
            </section>

          </div>
        </div>
      </div>

      {/* Footer */}
      <div className="bg-gray-800 border-t border-gray-700 mt-16">
        <div className="max-w-4xl mx-auto px-4 py-6">
          <div className="flex flex-col sm:flex-row justify-between items-center space-y-4 sm:space-y-0">
            <div className="text-gray-400 text-sm">
              © 2025 Zuexis. All rights reserved.
            </div>
            <div className="flex space-x-6">
              <Link to="/privacy" className="text-gray-400 hover:text-purple-400 transition-colors text-sm">
                Privacy Policy
              </Link>
              <Link to="/terms" className="text-gray-400 hover:text-purple-400 transition-colors text-sm">
                Terms of Service
              </Link>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TermsOfServicePage;
